### ISSUE TITLE
No match found for 'SCF Energy', found 'RMS' when using tsopt with g16

### ISSUE THREAD

**Issue by timcypresswong** [eljost/pysisyphus#183] opened 2022-02-14 10:18 UTC
Dear Developers,

I encountered a problem when using tsopt function (pysisyphus ver: 0.7.4) with g16, the following is my input:

```python
tsopt:
  type: rsirfo
  do_hess: True
  hessian_recalc: 1
  prim_coord: [A, 0, 1, 2]
  rx_mode: [[[A, 0, 1, 2],1]]
  thresh: gau_tight
calc:
  type: g16
  pal: 36
  route: "wb97XD/def2svp"
  charge: 0
  mult: 1
geom:
  type: redund
  fn: splined_hei.xyz
```
The error message gives:
```
Consider checking the log files there.

Traceback (most recent call last):
...
...
...
pyparsing.exceptions.ParseException: No match found for 'SCF Energy', found 'RMS' (at char 57231), (line:780, col:1)
```
However, when I checked the .fchk file in crash_calculator_000 directory, the keyword 'SCF Energy' was actually there:
```
#gaussian16.fchk
...
...
-777: Virial Ratio          .............
-778: SCF Energy         .............
-779: Total Energy       ..............
-780: RMS Force         ...............
-781: RMS Density       ................
...
...
```
and the g16 job also terminate normally.
What could be the possible reason for this, and how can I make it work?

Best,
Tim

**Comment by eljost** [comment] 2022-02-14 12:39
The problem seems to be the order of entries in the .fchk-file and the order the parser expects. pysisyphus expects "SCF Energy" after "Total Energy", while in the .fchk "Total Energy" comes after "SCF Energy".

The issue is fixed in the current development version of pysisyphus. If the test suite passes I'll do a new release soon.

**Comment by timcypresswong** [comment] 2022-02-14 13:45
Thanks for the quick reply! Looking forward to a new release soon!

**Closed** 2022-02-22 08:24 UTC
